### ISSUE TITLE
What are the responsibilities of a maintainer?

### ISSUE THREAD

**Issue by richrd** [thelounge/thelounge-theme-zenburn#6]
I use this theme and love what you all have done with thelounge! I'm now running v3.0.0-pre7 and it feels really nice.

I was thinking that I could possibly maintain this theme if you want, but I'm not entirely sure what all the responsibilities are. I guess updating it to support new features, publish new versions to npm etc?

**Comment by AlMcKinlay** [comment]
Yeah, essentially what would be needed is someone to keep the theme up to date when css or html changes in the lounge, and then keeping versions up to date in npm.

It probably doesn't need many new features, just properly themeing new stuff from the lounge and updating when we break stuff with themes (which hopefully won't happen very often).

**Comment by astorije** [comment]
I second what @McInkay said. By supporting new features, I'm guessing you meant making sure theme works follows new features of The Lounge, in which case, yes, that's pretty much it :)
Reviewing/merging potential PRs, helping fixing bugs if necessary, etc. Publishing new versions should be very easy as it's automatically handled by Travis CI when creating a tag.

Feel free to stick around, subscribe to this repo to be notified of new issues / PRs, review existing PRs, open new ones if you want, etc. If that sounds like something you'd enjoy, you can become a project owner of this repo and get to make executive decisions 😁

**Comment by richrd** [comment]
Sounds good! I'm in :)
